name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'AlexKharenko'
        reponame: 'AlexKharenko.github.io'
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        VUE_APP_I18N_LOCALE: ${{ secrets.VUE_APP_I18N_LOCALE }}
        VUE_APP_I18N_FALLBACK_LOCALE: ${{ secrets.VUE_APP_I18N_FALLBACK_LOCALE }}
        VUE_APP_SERVER: ${{ secrets.VUE_APP_SERVER }}
